kuber_dir: "~/kubernetes"
file_url: "https://github.com/containerd/containerd/releases/download/v2.2.0/containerd-2.2.0-linux-amd64.tar.gz"
file_dest: "~/kubernetes"
containerd_version: "2.2.0"
runc_url: "https://github.com/opencontainers/runc/releases/download/v1.4.0/runc.amd64"
cni_url: "https://github.com/containernetworking/plugins/releases/download/v1.8.0/cni-plugins-linux-amd64-v1.8.0.tgz"
cni_plugin: "cni-plugins-linux-amd64-v1.8.0.tgz"
kubernetes_repo_key: "https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key"
kubernetes_repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
cluster_version: "1.32.9-1.1"
